log:
  level: debug
  disable_sentry: true

inet_listener:
  disabled: false
  ip: 0.0.0.0
  port: 8000

vsock_listener:
  disabled: false
  context_id: 0
  port: 8000

signer:
  attestations_directory: "/shared/attestations"
