package tests

import (
	"github.com/distributed-lab/aws-nitro-enclaves-av/internal/pkg/icrypto"
	"github.com/distributed-lab/aws-nitro-enclaves-av/internal/pkg/utils"
	"github.com/ethereum/go-ethereum/signer/core/apitypes"
)

const testAttDoc = "hEShATgioFkRh79pbW9kdWxlX2lkeCdpLTAwOWExZDdiM2RhNjFjMDYwLWVuYzAxOThiYzU3MWJmM2U3ODVmZGlnZXN0ZlNIQTM4NGl0aW1lc3RhbXAbAAABmLxXhrNkcGNyc7AAWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADWDAU2HVqhk7XOk3e2c/JWZfvK2DP5fRQ5qd8P4viubXB9/vcicYKEeBZPCgjjoCTVasEWDDTYNLhTmkPa2PEAPsYa/rseapKHBiI1jxEBq/nvhKyaovC3rIfxoa/6ppHyyIO5+4FWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPWDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABrY2VydGlmaWNhdGVZAoAwggJ8MIICAaADAgECAhABmLxXG/PnhQAAAABooudNMAoGCCqGSM49BAMDMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxOTA3BgNVBAMMMGktMDA5YTFkN2IzZGE2MWMwNjAudXMtZWFzdC0xLmF3cy5uaXRyby1lbmNsYXZlczAeFw0yNTA4MTgwODQxNDZaFw0yNTA4MTgxMTQxNDlaMIGTMQswCQYDVQQGEwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjEQMA4GA1UEBwwHU2VhdHRsZTEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxPjA8BgNVBAMMNWktMDA5YTFkN2IzZGE2MWMwNjAtZW5jMDE5OGJjNTcxYmYzZTc4NS51cy1lYXN0LTEuYXdzMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEbl9H2IopOGUrTSiMfWl1kqC3lrvHhmc3y4P4LXcBY4OBktpApu5XOKQD4yReb/57uYtNefpWV4i4/3HUa129i7fhf4CeNLb6btiEpaJLJ8aqQfUrPV14z+4ETY8njardox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDAKBggqhkjOPQQDAwNpADBmAjEAzO7mCoiYVe0KshclnoDZsqNd5/0OyMl/hFqGdfz3SgO3xKjAFG/Qv3UuCtHn1XF9AjEA5wDgu5BscJrGC6zqxHcrGfXCwczCfKfYXW6fUf+sWQMSa9d2PRUZyWQJSDaxmjc+aGNhYnVuZGxlhFkCFTCCAhEwggGWoAMCAQICEQD5MXVoG5Cv4R1GzLTk5/hWMAoGCCqGSM49BAMDMEkxCzAJBgNVBAYTAlVTMQ8wDQYDVQQKDAZBbWF6b24xDDAKBgNVBAsMA0FXUzEbMBkGA1UEAwwSYXdzLm5pdHJvLWVuY2xhdmVzMB4XDTE5MTAyODEzMjgwNVoXDTQ5MTAyODE0MjgwNVowSTELMAkGA1UEBhMCVVMxDzANBgNVBAoMBkFtYXpvbjEMMAoGA1UECwwDQVdTMRswGQYDVQQDDBJhd3Mubml0cm8tZW5jbGF2ZXMwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT8AlTrpgjB82hw4prakL5GODKSc26JS//2ctmJREtQUeU0pLH22+PAvFgaMrexdgcO3hLWmj/qIRtm51LPfdHdCV9vE3D0FwhD2dwQASHkz2MBKAlmRIfJeWKEME3FP/SjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFJAltQ3ZBUfnlsOW+nKdz5mp30uWMA4GA1UdDwEB/wQEAwIBhjAKBggqhkjOPQQDAwNpADBmAjEAo38vkaHJvV7nuGJ8FpjSVQOOHwND+VtjqWKMPTmAlUWhHry/LjtV2K7ucbTD1q3zAjEAovObFgWycCil3UugabUBbmW0+96P4AYdalMZf5za9dlDvGH8K+sDy2/ujSMC89/2WQLDMIICvzCCAkWgAwIBAgIRALAXK5jEcyRhqD/971YU60AwCgYIKoZIzj0EAwMwSTELMAkGA1UEBhMCVVMxDzANBgNVBAoMBkFtYXpvbjEMMAoGA1UECwwDQVdTMRswGQYDVQQDDBJhd3Mubml0cm8tZW5jbGF2ZXMwHhcNMjUwODE0MDQwNzQ1WhcNMjUwOTAzMDUwNzQ1WjBkMQswCQYDVQQGEwJVUzEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxNjA0BgNVBAMMLWJlYzc4ZDg1YTcwNjRiYjcudXMtZWFzdC0xLmF3cy5uaXRyby1lbmNsYXZlczB2MBAGByqGSM49AgEGBSuBBAAiA2IABDSloPYPwhDrh4bvHoVvlEsjtyegWZ+xq8beWo6NzggEyq7Hu3nZ97IFBMZEeOJ2CxcBsrPIID1kAGjhHzxAS0FhLD+728q++YqkbnqJEktAsF5iyMc3gkMZA6L/j/r0F6OB1TCB0jASBgNVHRMBAf8ECDAGAQH/AgECMB8GA1UdIwQYMBaAFJAltQ3ZBUfnlsOW+nKdz5mp30uWMB0GA1UdDgQWBBTE1rg1pJWpAwQdx/hJ4nrWTZ1sYDAOBgNVHQ8BAf8EBAMCAYYwbAYDVR0fBGUwYzBhoF+gXYZbaHR0cDovL2F3cy1uaXRyby1lbmNsYXZlcy1jcmwuczMuYW1hem9uYXdzLmNvbS9jcmwvYWI0OTYwY2MtN2Q2My00MmJkLTllOWYtNTkzMzhjYjY3Zjg0LmNybDAKBggqhkjOPQQDAwNoADBlAjBI98ROYSPbaDb+GiNMbEBfDJr/ISfCmOWzfgwNAQt2lOxsqocN9Gskwp2/L92m7+ICMQDp9OQB8xHn0X8WlVif+0J34SFk009cwXsLA+QW1EcL3x9u1iU4RPmDOq/HbRtT0b9ZAxowggMWMIICm6ADAgECAhEA0zysB8N91jhqEFNASSxI+TAKBggqhkjOPQQDAzBkMQswCQYDVQQGEwJVUzEPMA0GA1UECgwGQW1hem9uMQwwCgYDVQQLDANBV1MxNjA0BgNVBAMMLWJlYzc4ZDg1YTcwNjRiYjcudXMtZWFzdC0xLmF3cy5uaXRyby1lbmNsYXZlczAeFw0yNTA4MTgwMjI0MjlaFw0yNTA4MjMxNTI0MjlaMIGJMTwwOgYDVQQDDDM2YWQ5ODg2OWRmMDdhMGNjLnpvbmFsLnVzLWVhc3QtMS5hd3Mubml0cm8tZW5jbGF2ZXMxDDAKBgNVBAsMA0FXUzEPMA0GA1UECgwGQW1hem9uMQswCQYDVQQGEwJVUzELMAkGA1UECAwCV0ExEDAOBgNVBAcMB1NlYXR0bGUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQ7LPH7KemBNZ0D4vMO2rVDqq6IaBs9rdC/lWw7UbEhg6kNrnU6dERrqi5gbf6XPEftZsEjRhNYsjMGOqJ81hFkkz1b4q3E1Rhfepmltmd6740/B8s3WVQ2y2Ya0Ve3Xv6jgeowgecwEgYDVR0TAQH/BAgwBgEB/wIBATAfBgNVHSMEGDAWgBTE1rg1pJWpAwQdx/hJ4nrWTZ1sYDAdBgNVHQ4EFgQU59bh5+/J33gJkVZm2S0QsLK5uh8wDgYDVR0PAQH/BAQDAgGGMIGABgNVHR8EeTB3MHWgc6Bxhm9odHRwOi8vY3JsLXVzLWVhc3QtMS1hd3Mtbml0cm8tZW5jbGF2ZXMuczMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vY3JsL2ZkMzNiNzA2LTYzYzctNDM3NC1hY2MxLTU3M2I3ZGM3ZDliZS5jcmwwCgYIKoZIzj0EAwMDaQAwZgIxALWV/n0UQpNRlNyq/kqUMeg/lJM3m5w8Oq7v2qww4e/TFIh/HVyHehQZaxuOEdruZgIxAONWEbbVfFSIUhvEE13y01tjX+/vImx+EohPZfTRT7l5QOTkF25utLVk6Ajh7nWU41kCwjCCAr4wggJFoAMCAQICFQC3K4B7vI+7eylB3+Pq00YDO+SSXTAKBggqhkjOPQQDAzCBiTE8MDoGA1UEAwwzNmFkOTg4NjlkZjA3YTBjYy56b25hbC51cy1lYXN0LTEuYXdzLm5pdHJvLWVuY2xhdmVzMQwwCgYDVQQLDANBV1MxDzANBgNVBAoMBkFtYXpvbjELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdTZWF0dGxlMB4XDTI1MDgxODAzNDAwNVoXDTI1MDgxOTAzNDAwNVowgY4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApXYXNoaW5ndG9uMRAwDgYDVQQHDAdTZWF0dGxlMQ8wDQYDVQQKDAZBbWF6b24xDDAKBgNVBAsMA0FXUzE5MDcGA1UEAwwwaS0wMDlhMWQ3YjNkYTYxYzA2MC51cy1lYXN0LTEuYXdzLm5pdHJvLWVuY2xhdmVzMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEp5J8e0yGnGvFgjIlAS08OEQald0NEIKs58ZrtIMSIXerc1Wf3+AUag6tTI0HW9x1que+JKKzJqwqctOEPFTqrKEArZSyTZnKAS9noPSXA2HzM4UH0R0hBMX4zWrXR6Ino2YwZDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwICBDAdBgNVHQ4EFgQUxCio2pWXDxQ2X+JtPswq24bG9R0wHwYDVR0jBBgwFoAU59bh5+/J33gJkVZm2S0QsLK5uh8wCgYIKoZIzj0EAwMDZwAwZAIwXgtkwa7oALFLQaqe70JoWpK/YfFNWDDdbVBPQ26tOYB8g7BfN6EB+lEazK3lsgohAjBiF4z55ZGMYS+dJkJWiCtNjIYYlFZd1V5YH0DqpLV7gk8wkByNCBlMvjJ0udHE1nhqcHVibGljX2tleVhBBCimQGo5aD4SfRPgADvdb+KMRxitViJAuQy/Rf90XCmioBWnkv2yWBO21NL8BglFhL0KoDlReiVAtdio0gFRuGRpdXNlcl9kYXRhWEEEKKZAajloPhJ9E+AAO91v4oxHGK1WIkC5DL9F/3RcKaKgFaeS/bJYE7bU0vwGCUWEvQqgOVF6JUC12KjSAVG4ZGVub25jZfb/WGA4/TmsroBiltBO4FSaOOXHS12o6H+OGl3ZQzNhPA6rf/hpgJrkEWjfX+K3+ek9Y7GeJjfkl0bpKm1NMOmIaUMCBxoeHkuT3tgtOWwLQvB0gWWpxlUfxAXjzEKzpogcbYs="
const addressAttDocPath = "/export/attestation-verifier/attestations/address.coses1"

var domain = icrypto.Domain{
	TypedDataDomain: apitypes.TypedDataDomain{
		Name:    "Test",
		Version: "v1",
	},
	DomainTypes: []apitypes.Type{
		{Name: "name", Type: "string"},
		{Name: "version", Type: "string"},
	},
}

var tests = []struct {
	name                string
	primaryType         *string
	fields              []string
	attestationDocument string
	wantErr             bool
}{
	{
		name:                "Custom PrimaryType and Fields",
		primaryType:         utils.AsPointer("Pt"),
		fields:              []string{"pcr0"},
		attestationDocument: testAttDoc,
		wantErr:             false,
	},
	{
		name:                "Default PrimaryType and custom Fields",
		primaryType:         nil,
		fields:              []string{"pcr0", "user_data"},
		attestationDocument: testAttDoc,
		wantErr:             false,
	},
	{
		name:                "Default PrimaryType and Fields",
		primaryType:         nil,
		fields:              nil,
		attestationDocument: testAttDoc,
		wantErr:             false,
	},
	{
		name:                "Custom PrimaryType and default Fields",
		primaryType:         utils.AsPointer("Custom"),
		fields:              nil,
		attestationDocument: testAttDoc,
		wantErr:             false,
	},
	{
		name:                "Absent requested field",
		primaryType:         utils.AsPointer("Custom"),
		fields:              []string{"nonce"},
		attestationDocument: testAttDoc,
		wantErr:             true,
	},
}
